config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup',}

  devise_for :admin, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',},
    :controllers => {registrations:  "admins/registrations"}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  get 'nagesynchros/index'
  get 'nagesynchros/show'
  get 'polos/index'
  get 'polos/show'

  resources :profils, only: [:show]


  get 'staticswims/show'
  get 'staticswims/index'
  get 'adultes/show'
  get 'adultes/index'

  get 'ecoles/index'
  get 'ecoles/show'

  get 'reservationstatics/_form'
  get 'reservationstatics/new'
  get 'reservationstatics/show'
  get 'reservationstatics/index'

  get 'reservationcours/_form'
  get 'reservationcours/new'
  get 'reservationcours/show'
  get 'reservationcours/index'

  get 'reservationgyms/_form'
  get 'reservationgyms/edit'
  get 'reservationgyms/show'
  get 'reservationgyms/index'

  get 'charges/new'
  get 'charges/create'
  get 'paiements/new'
  get 'paiements/create'

  get 'reservationpalmes/_form'
  get 'rreservationpalmes/index'
  get 'reservationpalmes/show'
  get 'reservationpalmes/new'

  get 'reservationads/_form'
  get 'reservationads/edit'
  get 'reservationads/show'
  get 'reservationads/index'

  get 'reservationboxings/_form'
  get 'reservationboxings/index'
  get 'reservationboxings/show'
  get 'reservationboxings/new'

  get 'reservationjards/_form'
  get 'reservationjards/index'
  get 'reservationjards/show'
  get 'reservationjards/new'

  get 'reservationsynchros/_form'
  get 'reservationsynchros/index'
  get 'reservationsynchros/show'
  get 'reservationsynchros/new'

  resources :charges
  resources :paiements
  resources :adhesions , only: [:show, :new, :create]
  resources :nagesynchros , only: [:index, :show]
  resources :aquaboxings , only: [:index, :show]
  resources :jardins , only: [:index, :show]
  resources :nagepetits , only: [:index, :show]
  resources :aquabikes , only: [:index, :show]
  resources :aquaparcours , only: [:index, :show]
  resources :palmes , only: [:index, :show]
  resources :adultes , only: [:index, :show]
  resources :staticswims , only: [:index, :show]
  resources :aquagyms , only: [:index, :show]
  resources :ecoles , only: [:index, :show]
  resources :polos , only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create]
  resources :reservationgyms, only: [:index, :show, :new, :create]
  resources :reservationads, only: [:index, :show, :new, :create]
  resources :reservationpalmes, only: [:index, :show, :new, :create]
  resources :reservationstatics, only: [:index, :show, :new, :create]
  resources :reservationcours, only: [:index, :show, :new, :create]
  resources :reservationboxings, only: [:index, :show, :new, :create]
  resources :reservationpetits, only: [:index, :show, :new, :create]
  resources :reservationjards, only: [:index, :show, :new, :create]
  resources :reservationecoles, only: [:index, :show, :new, :create]
  resources :reservationpolos, only: [:index, :show, :new, :create]
  resources :reservationsynchros, only: [:index, :show, :new, :create]
  resources :selected_resa, only: [:create, :destroy]

  get 'pages/mention' , to: "pages#mention"
  get 'pages/apropos', to: "pages#apropos"
  get 'pages/aquaphobie' , to: "pages#aquaphobie"

  root :to => "pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/helpers/reservationgyms_helper.rb
module ReservationgymsHelper
end

app/models/reservationgym.rb
class Reservationgym < ApplicationRecord
  validate :limit_personne
  belongs_to :aquagym
  before_create :set_nb_resa


  def self.list_creneau
    ["selectionnez un créneau", "Mardi 19h05 - 20h", "Jeudi 19h05 - 20h", "Samedi 13h - 13h45"]
  end

  def self.creneau_limit
    {
      "Mardi 19h05 - 20h" => 12,
      "Jeudi 19h05 - 20h" => 12,
      "Samedi 13h - 13h45" => 12
    }
  end

  def limit_personne
    if Reservationgym.creneau_limit[creneau] ==  Reservationgym.where(creneau: creneau).count
      errors.add(:creneau, "Ce créneau est complet")
    end
  end

  def self.list_events
    {
       0 => [], #dimanche
       1 => [], #lundi
       2 => ["19h05 - 20h"], #mardi
       3 => [], #mercredi
       4 => ["19h05 - 20h"], #jeudi
       5 => [], #vendredi
       6 => ["13h - 13h45"], #samedi
    }
  end

  private

  def set_nb_resa
   self.nb_resa = self.aquagym.nbseance
  end
end

app/controllers/reservationgyms_controller.rb
class ReservationgymsController < ApplicationController
  before_action :set_reservationgym, only: [:show, :destroy, :edit, :update]
  before_action :authenticate_user!

  def index
    @reservationgyms = Reservationgym.includes(:aquabike).all
  end

  def show
  end

  def destroy
    @reservationgyms.destroy
    head :ok
  end

  def edit
  end

  def update
    @reservationgym.update(reservationgym_params)
    redirect_to reservationgym_path(@reservationgym)
  end

  def new
    @aquagym = Aquagym.find(params[:aquagym_id])
    @reservationgym = Reservationgym.new
    @selected_resa = SelectedResa.where(user_id: current_user.id, resource_id: @aquagym.id, resource_type: 'Aquagym')
    @selected_resa_count = Reservationgym.where(aquagym_id: @aquagym.id, user_id: current_user.id).sum(:nb_resa) - @selected_resa.count
  end

  def create
    @reservationgym = Reservationgym.create(reservationgym_params)
    if @reservationgym.errors.count > 0
      flash[:danger] = @reservationgym.errors.full_messages.join(',')
      redirect_to new_reservationgym_path(aquagym_id: @reservationgym.aquagym_id)
    else
      aquagym = @reservationgym.aquagym
      if aquagym
        price = aquagym.price
        if price
          @reservationgym.price = aquagym.price
        else
          flash[:danger] = 'Vous avez mal renseigné les champs de textes !'
        end
        @reservationgym.save
        AdminMailer.info_resa_aquagym(@reservationgym).deliver_now
     end
     redirect_to reservationgym_path(@reservationgym)
   end
  end

  def reservationgym_params
    params.require(:reservationgym).permit(:start, :price, :aquagym_id, :name, :phone, :creneau )
  end

  def set_reservationgym
    @reservationgym = Reservationgym.find(params[:id])
  end

end

app/views/reservationgyms/_form.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h3 class="title_résa">Pour faire une réservation choisissez une date et un créneau</h3>
    </div>
  </div>
  <div class="row" id="content_reservation">
    <div class="col-md-6 col-sm-6 col-xs-12" >
      <%= form_for([@aquagym, @aquagym.reservationgyms.new]) do |f| %>
      <div class="col-md-6 ">
        <label for="">choisissez une date</label>
        <%= f.date_field :start,  class: "form-control"%>
    </div>
    <div class="col-md-6">
      <label for="">Entrez votre nom complet</label>
      <%= f.text_field :name, placeholder: 'ex :Dimiti payet',  class: "form-control"  %>
    </div>
    <div class="col-md-6">
      <label for="">Entrez votre numero de téléphone</label>
      <%= f.text_field :phone, placeholder: 'ex 0692 12 33 44',  class: "form-control"  %>
    </div>
    <div class="col-md-6">
      <label for="">Sélectionnez un créneau</label>

    <%= f.select :creneau, ["selectionnez un créneau", "Mardi 19h05 - 20h", "Jeudi 19h05 - 20h", "Samedi 13h - 13h45"] ,{},{ :class => "form-control"}%>
    </div>
      </div>
       <div class="col-md-6 col-sm-6 col-xs-12">
          <%= f.hidden_field :aquagym_id, value: @aquagym.id %>
      </div>
            <div class="text-center">
              <%= f.submit 'Validez votre location', :class => "btn btn-primary navbar-btn"%>
            </div>
      <% end %>
  </div>
</div>
 <script>
 $(function() {
        $('#start').datepicker({
                    dateFormat: 'dd-mm-yy',
                    monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août',
                    'Septembre','Octobre','Novembre','Décembre'],
                    dayNamesMin: ['D','L','M','M','J','V','S'],
                    minDate: 0,
                    maxDate: '1m',
                    onSelect: function(selected) {
                        var newdate = new Date($("#start").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                    }
        });
    })
</script>

app/views/reservationgyms/edit.html.erb
<h1>Reservationgyms#edit</h1>
<p>Find me in app/views/reservationgyms/edit.html.erb</p>

app/views/reservationgyms/index.html.erb
<h1>Reservationgyms#index</h1>
<p>Find me in app/views/reservationgyms/index.html.erb</p>

app/views/reservationgyms/new.html.erb
<section id="banner_charges" data-blink-id="pvb1pxmp5cau7rq4c24yp" style="background-size: cover;background-position: center center;background-repeat: no-repeat;background-image: url(/piscine.jpg);" >
  <main class="resa">
    <div class="container">
      <div class="row" id="content_page_index">
        <div class="col-lg-12 col-sm-12 col-xs-12" id="content_page_show">
          <div class="text-center">
            <h3 class="title_résa-index">Pour faire une réservation choisissez une date et un créneau</h3>
          </div>

          <h1 class="msg_flash"><%= flash[:danger ]%></h1>
          <div class="row">
            <div class="row margin-top">
              <%= week_calendar number_of_weeks: 1 do |date| %>
                <%= date.day %>
                <% next if date < Time.now.yesterday %>
                <% Reservationgym.list_events[date.wday]&.each do |meeting| %>
                  <div class="margin-top">
                    <% next if SelectedResa.where(resource_id: @aquagym.id).where("date = ? AND title = ?",  DateTime.parse(date.to_s), meeting).count >= @aquagym.nbpers%>
                    <%= link_to selected_resa_index_path(resource_id: @aquagym.id, date: date, title: meeting, resource_name: 'Reservationgym', resource_type: 'aquagym_id', resa_url: aquagym_path(@aquagym)), method: :post, remote: true do  %>
                      <button type="button" class="btn btn-primary">
                        <%= meeting %>
                      </button>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div id="selected_resa">
              <%= render partial: 'selected_resa/selected_resa', locals: {resource_name: 'Reservationgym', resource_type: 'aquagym_id', resa_url: aquagym_path(@aquagym)} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</section>

app/views/reservationgyms/show.html.erb
<section id="banner_charges" data-blink-id="pvb1pxmp5cau7rq4c24yp" style="background-size: cover;background-position: center center;background-repeat: no-repeat;background-image: url(/play.jpg);" >
<div class="container-fluid show">
 <div class="fond">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6 col-xs-offset-1 col-xs-10" id="zone_show_resa">
      <div class="text-center">
        <h3 class="title_show">Récapitulatif de votre réservation popur aquagym </h3>
      </div>

      
      <h3>Vous avez réservé pour le : <%= @reservationgym.start %> </h3>
      <h3>Le créneau de : <%= @reservationgym.creneau %></h3>
      <h4>Prix total : <span><%= @reservationgym.price %> euros</span></h4><br/>
      <div class="text-center">
      <h3><%= link_to 'Passez au paiement', new_charge_path(reservationgym_id: @reservationgym.id) , class:"btn btn-info btn-rounded btn-lg" %></h3><br/>
      </div>
  </div>
 </div>
 </div>
</div>
</section>