config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup',}

  devise_for :admin, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup',},
    :controllers => {registrations:  "admins/registrations"}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  get 'nagesynchros/index'
  get 'nagesynchros/show'
  get 'polos/index'
  get 'polos/show'

  resources :profils, only: [:show]


  get 'staticswims/show'
  get 'staticswims/index'
  get 'adultes/show'
  get 'adultes/index'

  get 'ecoles/index'
  get 'ecoles/show'

  get 'reservationstatics/_form'
  get 'reservationstatics/new'
  get 'reservationstatics/show'
  get 'reservationstatics/index'

  get 'reservationcours/_form'
  get 'reservationcours/new'
  get 'reservationcours/show'
  get 'reservationcours/index'

  get 'reservationgyms/_form'
  get 'reservationgyms/edit'
  get 'reservationgyms/show'
  get 'reservationgyms/index'

  get 'charges/new'
  get 'charges/create'
  get 'paiements/new'
  get 'paiements/create'

  get 'reservationpalmes/_form'
  get 'rreservationpalmes/index'
  get 'reservationpalmes/show'
  get 'reservationpalmes/new'

  get 'reservationads/_form'
  get 'reservationads/edit'
  get 'reservationads/show'
  get 'reservationads/index'

  get 'reservationboxings/_form'
  get 'reservationboxings/index'
  get 'reservationboxings/show'
  get 'reservationboxings/new'

  get 'reservationjards/_form'
  get 'reservationjards/index'
  get 'reservationjards/show'
  get 'reservationjards/new'

  get 'reservationsynchros/_form'
  get 'reservationsynchros/index'
  get 'reservationsynchros/show'
  get 'reservationsynchros/new'

  resources :charges
  resources :paiements
  resources :adhesions , only: [:show, :new, :create]
  resources :nagesynchros , only: [:index, :show]
  resources :aquaboxings , only: [:index, :show]
  resources :jardins , only: [:index, :show]
  resources :nagepetits , only: [:index, :show]
  resources :aquabikes , only: [:index, :show]
  resources :aquaparcours , only: [:index, :show]
  resources :palmes , only: [:index, :show]
  resources :adultes , only: [:index, :show]
  resources :staticswims , only: [:index, :show]
  resources :aquagyms , only: [:index, :show]
  resources :ecoles , only: [:index, :show]
  resources :polos , only: [:index, :show]
  resources :reservations, only: [:index, :show, :new, :create]
  resources :reservationgyms, only: [:index, :show, :new, :create]
  resources :reservationads, only: [:index, :show, :new, :create]
  resources :reservationpalmes, only: [:index, :show, :new, :create]
  resources :reservationstatics, only: [:index, :show, :new, :create]
  resources :reservationcours, only: [:index, :show, :new, :create]
  resources :reservationboxings, only: [:index, :show, :new, :create]
  resources :reservationpetits, only: [:index, :show, :new, :create]
  resources :reservationjards, only: [:index, :show, :new, :create]
  resources :reservationecoles, only: [:index, :show, :new, :create]
  resources :reservationpolos, only: [:index, :show, :new, :create]
  resources :reservationsynchros, only: [:index, :show, :new, :create]
  resources :selected_resa, only: [:create, :destroy]

  get 'pages/mention' , to: "pages#mention"
  get 'pages/apropos', to: "pages#apropos"
  get 'pages/aquaphobie' , to: "pages#aquaphobie"

  root :to => "pages#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aquaparcour.rb
class Aquaparcour < ApplicationRecord
  has_many :reservationcours, dependent: :destroy

end

app/controllers/aquaparcours_controller.rb
class AquaparcoursController < ApplicationController
  before_action :set_aquaparcour, only: [:show, :update, :destroy, :edit]

  def new
    @aquaparcour = Aquaparcour.new
  end
  def create
    @aquaparcour = Aquaparcour.create(aquaparcour_params)
    redirect_to aquaparcour_path(@aquaparcour)
  end
  def show
  end

  def update
    @aquaparcour.update(aquaparcour_params)
    rediredct_to aquaparcour_path(@aquaparcour)
  end

  def index
    @aquaparcours = Aquaparcour.all
  end
  def edit

  end
  def destroy
  end

  private

  def aquaparcour_params
    params.require(:aquaparcour).permit(:title, :price, :nbpers, :nbseance, :duree, :periode)
  end

  def set_aquaparcour
    @aquaparcour = Aquaparcour.find(params[:id])
  end
end

app/helpers/aquaparcours_helper.rb
module AquaparcoursHelper
end

app/views/aquaparcours/index.html.erb
<section id="banner" data-blink-id="pvb1pxmp5cau7rq4c24yp" style="background-size: cover;background-position: center center;background-repeat: no-repeat;background-image: url(/aquaparcours.JPG);" >
 <div class="banner-text">
  <h2 class="description-header">Aqua-parcours</h2>
 </div>
 <div class="dimmer"></div>
</section>

     <div class="container marketing">
      <div class="row">
        <div class="text-center">
          <h2 class="why">Pourquoi faire de l'aquabike ?</h2>
        </div>
        <div class="col-lg-4">
          <div class="text-center"><i class="fas fa-swimming-pool"></i></div>
           <p class="text">L’aquabike est le sport idéal si vous avez les articulations
             fragiles et plus particulièrement les genoux et si vous êtes en surpoids.
             Lorsque vous êtes dans l’eau, votre corps est en quasi-apesanteur
            et vous ne ressentez qu’un tiers de votre poids terrestre.
             Les risques de blessures et de chutes sont donc nuls.</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <div class="text-center"><i class="fas fa-smile-beam"></i></i></div>
          <p class="text">La monotonie n’est pas à l’ordre du jour. Vous pédalez
            dans différentes positions, accompagné d’un professeur et
             au rythme d’une musique. Les séances de 45 minutes à une
             heure vous permettent de vous muscler sans vous ennuyer.
          </p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <div class="text-center"><i class="fab fa-gratipay"></i></div>
          <p class="text">Les bienfaits de l’aquabike :
            Amélioration du système cardio-vasculaire,
            lutte contre la cellulite, raffermi la peau et
            muscle le bas du corps.
          </p>
        </div><!-- /.col-lg-4 -->
        <hr>
      </div><!-- /.row -->
</div>
 <section class="pricing py-5">
  <div class="container">
    <div class="row">
      <% @aquaparcours.each do | aquaparcour | %>
      <div class="col-lg-3">
      <div class="card mb-5 mb-lg-0">
        <div class="card-body">
          <h5 class="card-title text-muted text-uppercase text-center"><%=aquaparcour.title%></h5>
           <h6 class="card-price text-center"><%= aquaparcour.price%> € <span class="period">/La séance</span></h6>
          <hr>
          <ul class="fa-ul">
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%= aquaparcour.nbpers %> Personne(s)</li>
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%= aquaparcour.nbseance %> cours/semaine </li>
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%= aquaparcour.periode %> </li>
             <li><span class="fa-li"><i class="fas fa-check"></i></span><%= aquaparcour.duree %> minutes</li>
           </ul>
          <h4><%= button_to "Choisissez- moi ! ", aquaparcour_path(aquaparcour), :class => "btn btn-block btn-primary text-uppercase", :method => :get %></h4>
          </div>
        </div>
      </div>
      <% end %>

    </div>
  </div>
</section>

app/views/aquaparcours/show.html.erb
<article class="pricing py-5" id="banner" data-blink-id="pvb1pxmp5cau7rq4c24yp" style="background-size: cover;background-position: center center;background-repeat: ; height:700px; margin-bottom: 10px: no-repeat;background-image: url(/AQUAGYM.jpg);">
  <div class="container">
    <div class="row">
    <div class=" col-lg-offset-4 col-lg-4 col-sm-6 col-sm-offset-3 col-xs-12" id="content_page_show">
      <h3>Voici la formule que vous avez choisit</h3>
      <div class="card mb-5 mb-lg-0">
        <div class="card-body">
           <h5 class="card-title text-muted text-uppercase text-center"><%= @aquaparcour.title%></h5>
           <h6 class="card-price text-center"><%= @aquaparcour.price%> €<span class="period"><br>+  20 € de frais d'adhésion annuelle/La séance</span></h6>
          <hr>
          <ul class="fa-ul">
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%=@aquaparcour.nbpers %> Personne (s) maxi</li>
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%= @aquaparcour.nbseance %> cours/semaine </li>
            <li><span class="fa-li"><i class="fas fa-check"></i></span><%= @aquaparcour.periode %> Occasionnel </li>
             <li><span class="fa-li"><i class="fas fa-check"></i></span><%= @aquaparcour.duree %> minutes</li>
           </ul>
           <%= link_to 'Faire une réservation', new_reservationcour_path(aquaparcour_id: @aquaparcour.id), class: "btn btn-primary navbar-btn", id: "btn_car_show"%>
        </div>
       </div>
    </div>
  </div>
</div>
</article>